---
- name: Add user {{env_user}}
  user:
    name: "{{env_user}}"

- name: add necessary directories for php
  file:
    path: "{{ item }}"
    owner: "{{env_user}}"
    group: "{{env_user}}"
    state: directory
  loop:
     - /var/www/{{env_user}}/{{server_name}}
     - /var/lib/php/{{server_name}}/session
     - /var/lib/php/{{server_name}}/wsdlcache
     - /var/lib/php/{{server_name}}/upload

- name: create base config for nginx
  template:
    src: nginx/site.conf.j2
    dest: /etc/nginx/conf.d/{{server_name}}.conf
    owner: root
    group: root
    mode: 0644

- name: create config for php-fpm, php_version = {{php_version}}, type = {{php_installation_type}}
  when: (php_installation_type == "main")
  template:
    src: php-fpm.d/site.conf.j2
    dest: /etc/php-fpm.d/{{server_name}}.conf
    owner: root
    group: root
    mode: 0644

- name: create config for php-fpm, php_version = {{php_version}}, type = {{php_installation_type}}
  when: (php_installation_type == "additional")
  template:
    src: php-fpm.d/site.conf.j2
    dest: /etc/opt/remi/{{php_version}}/php-fpm.d/{{server_name}}.conf

- name: restart php-fpm
  when: (php_installation_type == "main")
  service: 
    name: php-fpm
    state: restarted
    
- name: restart php-fpm
  when: (php_installation_type == "additional")
  service:
    name: "{{php_version}}-php-fpm"
    state: restarted 

- name: restart nginx
  service:
    name: nginx
    state: restarted 
