- name: Playbook for Bitrix-ENV
  hosts: bx.bitchx.pw
  remote_user: root

  roles:
    - common
    - percona
    - nginx
    - firewalld
    - zabbix
    - { role: bitrix-env,
      tags: bitrix-env,
      bitrix_php_type: 'additional',
      bitrix_php_version: 'php72',
      bitrix_env_user: site1,
      bitrix_php_port: '9001',
      bitrix_server_name: site1.bitrix.ru,
      bitrix_mysql_db: 'site1' }
