---
- name: Ensure SELinux is set to disabled mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: "setenforce 0"
  ignore_errors: yes
  shell: setenforce 0
    
- name: check if exists epel.repo
  stat: 
    path: /etc/yum.repos.d/epel.repo
  register: epel

- name: Install EPEL REPO
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: epel.stat.exists == False
  
- name: install some basic stuff 
  yum:
    name:
      - ntp 
      - yum-utils 
      - vim
      - rsync 
      - mysql-connector-python
      - MySQL-python
      - python2-PyMySQL
      - wget
      - net-tools
      - tcpdump
      - sysstat
      - htop
      - atop
      - mc
      - git
      - bash-completion
      - bash-completion-extras
    state: present 

- name: enable service ntpd
  systemd:
    name: ntpd
    enabled: yes

- name: start ntpd
  service:
    name: ntpd
    state: started
