---
- name: Install EPEL REPO
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  
- name: install yum-utils vim rsync mysql-connector-python 
  yum:
    name: yum-utils, vim, rsync, mysql-connector-python
    state: present     
