---
- name: Install REMI REPO
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: php + modules for {{php_version}}, main installation
  when: (php_installation_type == "main")
  yum:
    name:
      - php-cli
      - php-fpm
      - php-xml
      - php-json
      - php-opcache
      - php-mysqlnd
      - php-common
      - php-fpm
      - php-pdo
      - php-gd
      - php-mbstring
      - php-pecl-zip
      - php-pecl-redis
      - php-soap
      - php-mcrypt
      - php-process
      - php-pear
      - php-pecl-memcache
    enablerepo: remi-{{php_version}}
    state: latest

- name: truncate www.conf for {{php_version}}
  copy: 
    dest: /etc/php-fpm.d/www.conf 
    content: ';empty for update' 
    backup: yes
  when: 
    - php_installation_type == "main"
    - php_disable_default_pool == True
    
- name: enable service php-fpm
  when: (php_installation_type == "main")
  systemd:
    name: php-fpm
    enabled: yes

- name: start php-fpm
  ignore_errors: yes
  when: (php_installation_type == "main")
  service:
    name: php-fpm
    state: started

- name: php + modules for {{php_version}}, additional installation
  when: (php_installation_type == "additional")
  yum:
    name:
      - "{{php_version}}-php-cli"
      - "{{php_version}}-php-fpm"
      - "{{php_version}}-php-xml"
      - "{{php_version}}-php-json"
      - "{{php_version}}-php-opcache"
      - "{{php_version}}-php-mysqlnd"
      - "{{php_version}}-php-common"
      - "{{php_version}}-php-fpm"
      - "{{php_version}}-php-pdo"
      - "{{php_version}}-php-gd"
      - "{{php_version}}-php-mbstring"
      - "{{php_version}}-php-pecl-zip"
      - "{{php_version}}-php-pecl-redis"
      - "{{php_version}}-php-soap"
      - "{{php_version}}-php-mcrypt"
      - "{{php_version}}-php-process"
      - "{{php_version}}-php-pear"
      - "{{php_version}}-php-pecl-memcache"

    enablerepo: remi-{{php_version}}
    state: present

- name: create directory for php-fpm logs, if doesnt exists
  file:
    path: /var/log/php-fpm/
    owner: root
    group: root
    state: directory

  
- name: truncate www.conf for {{php_version}}
  copy: 
    dest: /etc/opt/remi/{{php_version}}/php-fpm.d/www.conf 
    content: ';empty for update' 
    backup: yes
  when: 
    - php_installation_type == "additional"
    - php_disable_default_pool == True

- name: enable service php-fpm
  when: (php_installation_type == "additional")
  systemd:
    name: "{{php_version}}-php-fpm"
    enabled: yes

- name: start php-fpm
  ignore_errors: yes
  when: (php_installation_type == "additional")
  service:
    name: "{{php_version}}-php-fpm"
    state: started
