---
- name: Install Zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    state: present

- name: install Zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: Insert zabbix config
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf

- name: enable service Zabbix-agent
  systemd:
    name: zabbix-agent
    enabled: yes

- name: start Zabbix-agent
  ignore_errors: yes
  service:
    name: zabbix-agent
    state: started


